import logging
import smtplib
from email.mime.text import MIMEText
from email.mime.multipart import MIMEMultipart
from typing import Dict, Optional
from tenacity import retry, stop_after_attempt, wait_exponential

logger = logging.getLogger(__name__)


class SmtpClient:
    """SMTP client for sending emails to Remember the Milk."""
    
    def __init__(self, smtp_config: Dict):
        self.server = smtp_config.get("server", "")
        self.port = smtp_config.get("port", 587)
        self.use_tls = smtp_config.get("use_tls", True)
        self.username = smtp_config.get("username", "")
        self.password = smtp_config.get("password", "")
        self.from_email = smtp_config.get("from_email", self.username)
    
    @retry(stop=stop_after_attempt(3), wait=wait_exponential(multiplier=1, min=4, max=10))
    def send_email(self, to_email: str, subject: str, body: str, from_email: Optional[str] = None) -> bool:
        """Send email with retry logic."""
        sender_email = from_email or self.from_email
        if not sender_email:
            raise ValueError("No sender email address available")
        
        try:
            # Create message
            msg = MIMEMultipart()
            msg['From'] = sender_email
            msg['To'] = to_email
            msg['Subject'] = subject
            
            # Add body to email
            msg.attach(MIMEText(body, 'plain'))
            
            # Create SMTP session
            server = smtplib.SMTP(self.server, self.port)
            
            if self.use_tls:
                server.starttls()  # Enable security
            
            server.login(self.username, self.password)
            
            # Send email
            text = msg.as_string()
            server.sendmail(sender_email, to_email, text)
            server.quit()
            
            logger.info(f"Email sent successfully to {to_email}")
            return True
            
        except Exception as e:
            logger.error(f"Error sending email to {to_email}: {e}")
            raise  # Re-raise for retry logic
    
    def send_rtm_todo(self, rtm_email: str, todo_text: str, subject_tag: str, 
                      original_subject: str = "", original_sender: str = "") -> bool:
        """Send todo to Remember the Milk with proper formatting."""
        try:
            # Create subject line with RTM todo format and additional tag
            subject = f"{todo_text} {subject_tag}"
            
            # Create email body with original email context
            body_lines = [
                f"Todo: {todo_text}",
                "",
                "Original Email Context:",
                f"From: {original_sender}",
                f"Subject: {original_subject}",
                "",
                "Generated by IMAP AI Assistant"
            ]
            body = "\n".join(body_lines)
            
            # Send the email
            success = self.send_email(rtm_email, subject, body)
            
            if success:
                logger.info(f"RTM todo sent successfully: {todo_text}")
            else:
                logger.error(f"Failed to send RTM todo: {todo_text}")
            
            return success
            
        except Exception as e:
            logger.error(f"Error sending RTM todo: {e}")
            return False
    
    def test_connection(self) -> bool:
        """Test SMTP connection."""
        try:
            server = smtplib.SMTP(self.server, self.port)
            
            if self.use_tls:
                server.starttls()
            
            server.login(self.username, self.password)
            server.quit()
            
            logger.info("SMTP connection test successful")
            return True
            
        except Exception as e:
            logger.error(f"SMTP connection test failed: {e}")
            return False
